### ISSUE TITLE
Error parsing CSV

### ISSUE THREAD

**Issue by manicholls** [Etherhypnos/agent-haproxy-a0labs#1]
Hi,

I'm getting the following while parsing my stats:

Traceback (most recent call last):
  File "./agent-a0labs-newrelic", line 246, in run
    self.get_component_from_csv(reformat)
  File "./agent-a0labs-newrelic", line 191, in get_component_from_csv
    metrics = self.components[row['svname']]['metrics']
KeyError: 'metrics'

The CSV export is here:  http://pastebin.com/raw.php?i=JFkED72G

Hopefully that will help.

Thanks.

**Comment by ybriffa** [comment]
Hello,

Has the plugin ever succeeded to send the stats to newrelic ? Or you got this message the first time you used it ?

Best,

**Comment by manicholls** [comment]
I have not been able to get any instances to report in.  Thanks

**Comment by ybriffa** [comment]
Hi,

I tried to emulate your csv in local on my computer. I ran it with some errors that I fixed. Now it correctly gives me the correct json to send to newrelic. However, I did not get your error. I have also pushed the new version.

Can you confirm to me your are on a version of python 2.7 (python --version ?).

Best

**Comment by manicholls** [comment]
Your update works beautifully!  Thanks.

My python version is 2.7.6.

**Comment by ybriffa** [comment]
Glad to read it !

Hope you will enjoy the plugin, I let you close the issue if you have no more question,

Best
