### ISSUE TITLE
row['# pxname'] not in ret

### ISSUE THREAD

**Issue by bougui** [Etherhypnos/agent-haproxy-a0labs#2]
Hi,

I just installed youre pluging on centos 6 machine and when I run the agent I get

Traceback (most recent call last):
  File "./agent-a0labs-newrelic", line 258, in run
    reformat = self.reformat_csv(csv)
  File "./agent-a0labs-newrelic", line 126, in reformat_csv
    if (row['# pxname'] not in ret):
KeyError: '# pxname' 

My haproxy  (haproxy-1.5.4-2.el6_7.1) is up and is giving stats

I have python 2.7.5 on the server.

Can I ignore those errors ?

Thanks

**Comment by ybriffa** [comment]
Hello,

No you cannot, it won't send the data to NewRelic, can you paste me your csv export file that you get ?

**Comment by bougui** [comment]
Sorry about that,

In the config file I had not enter the haproxy stats port correctly, now I'm seeing info in NewRelic

Merci !

Guillaume
