### ISSUE TITLE
There is a newer version of the Haproxy plugin available.

### ISSUE THREAD

**Issue by bougui** [Etherhypnos/agent-haproxy-a0labs#3]
Hello,

I have the latest version I think where can I download a newver version so that I dont get this error in the newrelic portal ?

thanks

**Comment by ybriffa** [comment]
The latest version is normally the git, I'm going to look to this problem asap

**Comment by ybriffa** [comment]
Hello,

I've checked it out, something went wrong with the plugin version in the file configuration, I changed it so you can download it again. I also deleted output debug messages so it will not flood your output. You can also replace the script.

Sorry for have been that long,

Best,
